### ISSUE TITLE
Please explain the required hardware more

### ISSUE THREAD

**Issue by rdbrown1au** [AceCentre/morAce#36]
ConnectionDiagram.png shows:
 "Adafruit Feather nRF52840 Express" board
 2 x 10k Ohm resistors
1 Piezo buzzer 
1 Transistor
4 Switches

As an electronics novice, which Piezo buzzer and transistor should be used?

Vik Olliver's Arduino Microwriter recommends particular microswitches at https://www.thingiverse.com/thing:3433244
Do you have recommendations for particular switches for people to use, probably in a 3-switch Morse configuration?

Jon Oxer's https://github.com/SuperHouse/MOAC "Mini Open Adaptive Controller" may interest, if mono 3.5mm  AUDIO-JACK-PJ321 plugs are an AAC standard,  you could connect switches that way.

Currently the  "Adafruit Feather nRF52840 Express" is out of stock, but the smaller "Adafruit ItsyBitsy nRF52840 Express" isn't.
Do you know of any issues using the ItsyBitsy board?

**Comment by f1andrew** [comment]
> As an electronics novice, which Piezo buzzer and transistor should be used?

You need to use passive buzzer and npn transistor(for example 2n2222).
Your's transistor connection can look not exactly like on schematic because different transistors models can have different pinouts.
You need to check particular transistor pinout in datasheet. 
Transistor connection should be next:
Collector -> Buzzer
Base       -> D13 via resistor
Emitter    -> GND

> Do you know of any issues using the ItsyBitsy board?

Code was tested with ItsyBitsy too, so you can use that.

**Comment by willwade** [comment]
Any 3.5mm switches are fine :) 

Thanks for the interest - where did you hear of the project from? 


(NB: Soon we hope to provide a ready to go kit if its of interest - we are still in the testing phase of all this).

**Comment by willwade** [comment]
NB: For some reason the image wasnt updated in the docs: https://docs.acecentre.org.uk/products/v/morace/guides/developer-notes#arduino-wiring

**Comment by rdbrown1au** [comment]
Jim Lubin mentioned morAce to me in reply to an email asking about his mouse morse codes.
It would be nice if the Morse strings used were standardized and useful.. I'm not sure whether being completist and adding things like Middle Mouse button clicks & Mouse Scroll wheel support would be useful.
It's a pity that Micropython requires sending Shifts for standard, printable ASCII characters, which would change based on the configured Keyboard Language. Reading the Arduino stuff, it looks like printable ASCII (0x20..0x7E) is just sent straight. It might be worth testing that in Micropython if it's layering straight over the Ardiuno code. (Though looking at the HID code, probably not).

**Comment by willwade** [comment]
It’s complicated this. Standardisation is difficult because there’s a number of systems all ready been in place for years. Add to that people customise their codes heavily. I had thought we could create a tandemmaster or adap2u codeset. It wouldn’t be that hard.. 

It would be possible to do what you want. Bear in mind the ble hid library being used is sending a key code - it’s down to the receiving computer and it’s language code / keyboard setup as to what it sees. So to do what you want you’d have to create a middle layer function where eg ! = shift, 1. (Nb. This is pretty standard - take a look for example at this keymap codes for zmk which is a different project entirely built on the same hardware. It’s just the way a keyboard works https://zmk.dev/docs/codes) 

We could create a custom key map though. So you could just specify your us or uk or jpn etc -eg in the user config.   (@f1andrew like we do with relaykeys).

**Comment by willwade** [comment]
@rdbrown1au hope this suffices. Closing for now. Note we now support custom keymaps and sending strings like you want :)
